---

- name: install pip
  apt: name=python-pip update_cache=yes

- name: check pip.conf file
  shell: if [ ! -f /root/.pip/pip.conf ]; then mkdir /root/.pip/; touch /root/.pip/pip.conf;fi
      
- name: upgrade pip config file
  shell: echo "[global]\nindex-url=https://pypi.python.org/simple/\n\n[install]\ntrusted-host=mirrors.aliyun.com" > /root/.pip/pip.conf

- name: upgrade pip to latest version
  pip:
    name: pip
    extra_args: --upgrade
  
