- name: config ubuntu server
  hosts: itc
  remote_user: root
  vars:
      Trusty: deb https://apt.dockerproject.org/repo ubuntu-trusty main
      Xenial: deb https://apt.dockerproject.org/repo ubuntu-xenial main
      zabbix_agent_version: 3.0
  roles:
      #- provision-docker
      #- provision-certbot
        #- provision-vim
    - provision-zabbix-agent
        #- provision-nginx
