- name: config ubuntu server
  hosts: itc
  remote_user: root
  vars:
      Trusty: trusty
      Xenial: xenial
      zabbix_agent_version: 3.0
  roles:
      #- provision-docker
      - provision-pip
      - provision-certbot
        #- provision-vim
        #      - provision-zabbix-agent
      - provision-nginx
