---
- name: Install php PPA
  apt_repository: repo="ppa:ondrej/php" state=present

- name: Update cache
  apt: update_cache=yes

- name: install PHP
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5.6-fpm
    - php5.6-mysql
    - php5.6-curl
    - php5.6-gd
    - php5.6-imagick
