---
- name: install certbot on ubuntu 14.04
  get_url: url=https://dl.eff.org/certbot-auto dest=/root/
  when: ansible_distribution_version == '14.04'

- name: change certbot permissions on ubuntu 14.04
  file: 
      path=/root/certbot-auto mode=0755
  when: ansible_distribution_version == '14.04'

- name: install certbot on ubuntu 16.04
  apt: name=letsencrypt
  when: ansible_distribution_version == '16.04'

