---
#- name: upgrade system
#  apt: upgrade=dist update_cache=yes cache_valid_time=1800

- name: install apt-transport-https 
  apt: name=apt-transport-https state=present update_cache=yes cache_valid_time=900

- name: install ca-certificates
  apt: name=ca-certificates state=present update_cache=yes cache_valid_time=900

- name: install software-propertities-comman
  apt: name=software-properties-common state=present

  #- name: install curl
  #  apt: name=curl update_cache=yes

- name: add GPG key
  shell: curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -

- name: add key
  shell: apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D

  #- name: add docker repository
  #apt_repository: repo=deb https://apt.dockerproject.org/repo/ubuntu-$(lsb_release -cs) main state=present update_cache=yes

- name: install docker-engine 
  apt: name=docker-engine update_cache=yes cache_valid_time=3600 state=present

- name: restart docker-engine
  service: name=docker state=restarted

- name: install docker-compose
  apt: name=python-pip state=latest

- pip:
    name=docker-compose

- pip:
    name=virtualenv

